# Generated by Django 5.0.1 on 2024-01-12 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0007_alter_message_options_alter_reply_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favs',
            options={'ordering': ['-dateadded']},
        ),
    ]
