# Generated by Django 5.0.1 on 2024-01-13 03:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0008_alter_favs_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favs',
            name='movieid',
            field=models.IntegerField(),
        ),
    ]
