# Generated by Django 5.0.1 on 2024-01-07 08:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customusermodel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
